mode: "embedding-training-inference-evaluation"
version_name: "try14"

# incremental mode
data_source_A: "Data_example/fodors_zagats-tableA.csv"
data_source_B: "Data_example/fodors_zagats-tableB.csv"
ground_truth: "Data_example/fodors_zagats-matches.txt"
simulator_path: "services/dataStreamSimulator"
kafka:
  topicid: "entity_resolution_process"
  groupid: "er_group"
  bootstrap_servers: "localhost"
  port: 9092
  partitions: 3
  replication_factor: 1

  # sliding window strategy
  window_strategy: "count"       # "count" or "time"
  window_count: 26               # used if strategy is "count"
  update_frequency: 0            # 0 = tumbling window, otherwise stride size

## meta_path:list or list of list (several paths), * 'rid' should appear in meta_path if it is setted
# meta_path: ["name", "rid"]

# STATE MANAGEMENT
state_management:
# bert mode
  bert-dir: "data/bert"
# incremental mode. if execute several config files successively, the embedding_model-name (or version name) can not be the same
  graph-dir: "data/graph"
  graph-name: ""
  embedding-dir: "data/embedding"
  embedding_model-name: ""
  feature_index-dir: "data/index"
  feature_index-name: ""
  predicted_match-dir: "data/predicted"
  predicted_match-name: ""

# pipeline
normalization:

candidate_generation:
  status: True
  method: "fullindexing"
  data_pairs_fixed: ""

graph_construction:
  # node types explained in README
  node_types:
    - "5#__tn"                   # numerical instance
    - "5$__tt"                   # textual instance 
    - "5$__st"                   # instence after tokenization
    - "3$__idx"
    - "1$__cid"
  flatten: "tt"                  # split prefix for nodes
  smoothing_method: "no"         # smooth method: log/no
  directed: false                # whether the graph is directed
  ngram:                         # config node_type like ["5#__idx", "0#__cid", "0#__tt", "0#__tn", "0#__ng"] if ngram activated
    # token_n: [2, 3]
    # char_n: []
    # skip: 0                    # How many positions can there be between words when forming an n-gram


random_walk:
  write_walks: false
  walk_length: 30                # step size
  walks_number: 10               # number of sentences per root
  backtrack: false               # whether to allow return to previous node
  rw_stat: false                 # statistical result of random walk

embeddings_training:
  learning_method: "skipgram"    # skipgram / CBOW
  window_size: 3
  n_dimensions: 128
  training_algorithm: "word2vec" # word2vec / fasttext
  sampling_factor: 0.001
  
calculating_similarity:

decision_making:
  top_k: 10                      # top K most similar entries to keep
  simlist_n: 10                  # how many records to evaluate similarity for
  simlist_show: 5                # how many to print/show
  strategy_suppl: "basic"        # similarity algorithm: basic / faiss
  sim_structure: "graph"         # list / graph
  output_format: "graphml"            # db / json / parquet / graphml

bert_training:

bert_inference:

evaluation:

b_evaluation:
